language: go
sudo: false
go:
  - 1.11.x
  - 1.x

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
    - $HOME/Library/Caches/go-build

os:
  - linux
  - osx

before_install:
  - nvm install node
  - npm install -g npm

install:
  - npm --prefix client install

script:
  - node -v
  - npm -v
  # Run tests
  - go test -race -v -bench=. -coverprofile=coverage.txt -covermode=atomic ./...
  # Make
  - make build/static/index.html
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash)