language: go
sudo: false

go:
  - 1.11.x
  - 1.x
os:
  - linux
  - osx

before_install:
  - nvm install node
  - npm install -g npm

install:
  - npm --prefix client install

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
    - $HOME/Library/Caches/go-build

script:
  - node -v
  - npm -v
  # Run tests
  - go test -race -v -bench=. -coverprofile=coverage.txt -covermode=atomic ./...
  # Make
  - make build/static/index.html
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    # Release build configuration
    - name: release
      go:
        - 1.11.x
      os:
        - linux

      script:
        - node -v
        - npm -v
        # Run tests just in case
        - go test -race -v -bench=. ./...
        # Prepare releases
        - ./release.sh
        - ls -l dist

      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file:
          - dist/AdGuardHome-*.zip
          - dist/AdGuardHome-*.tar.gz
        on:
          repo: AdguardTeam/AdGuardHome
          branch: feature/travis_release_build
          # tags: true
        draft: true
        file_glob: true
        skip_cleanup: true